Entity/Traits/Ticket.php
<?php

namespace Hackzilla\Bundle\TicketBundle\Entity\Traits;

use Doctrine\Common\Collections\ArrayCollection;
use Hackzilla\Bundle\TicketBundle\Model\TicketMessageInterface;
use Hackzilla\Bundle\TicketBundle\Model\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Ticket.
 */
trait Ticket
{
    /**
     * @var int
     */
    protected $id;

    /**
     * @var int
     */
    protected $userCreated;
    protected $userCreatedObject;

    /**
     * @var int
     */
    protected $lastUser;
    protected $lastUserObject;

    /**
     * @var \DateTime
     */
    protected $lastMessage;

    /**
     * @Assert\NotBlank()
     *
     * @var string
     */
    protected $subject;

    /**
     * @var int
     */
    protected $status;

    /**
     * @var int
     */
    protected $priority;


    /**
     * @Assert\Count(min = "1")
     * @Assert\Valid()
     *
     * @var ArrayCollection
     */
    protected $messages;

    /**
     * @var \DateTime
     */
    protected $createdAt;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->messages = new ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set status.
     *
     * @param int $status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Set status string.
     *
     * @param string $status
     *
     * @return $this
     */
    public function setStatusString($status)
    {
        $status = \array_search(\strtolower($status), TicketMessageInterface::STATUSES);

        if ($status > 0) {
            $this->setStatus($status);
        }

        return $this;
    }

    /**
     * Get status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Get status string.
     *
     * @return string
     */
    public function getStatusString()
    {
        if (array_key_exists($this->status, TicketMessageInterface::STATUSES)) {
            return TicketMessageInterface::STATUSES[$this->status];
        }

        return TicketMessageInterface::STATUSES[0];
    }

    /**
     * Set priority.
     *
     * @param int $priority
     *
     * @return $this
     */
    public function setPriority($priority)
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * Set priority string.
     *
     * @param string $priority
     *
     * @return $this
     */
    public function setPriorityString($priority)
    {
        $priority = \array_search(\strtolower($priority), TicketMessageInterface::PRIORITIES);

        if ($priority > 0) {
            $this->setPriority($priority);
        }

        return $this;
    }

    /**
     * Get priority.
     *
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Get priority string.
     *
     * @return string
     */
    public function getPriorityString()
    {
        if (array_key_exists($this->priority, TicketMessageInterface::PRIORITIES)) {
            return TicketMessageInterface::PRIORITIES[$this->priority];
        }

        return TicketMessageInterface::PRIORITIES[0];
    }

    /**
     * Set userCreated.
     *
     * @param int|object $userCreated
     *
     * @return $this
     */
    public function setUserCreated($userCreated)
    {
        if (\is_object($userCreated)) {
            $this->userCreatedObject = $userCreated;
            $this->userCreated = $userCreated->getId();
        } else {
            $this->userCreatedObject = null;
            $this->userCreated = $userCreated;
        }

        return $this;
    }

    /**
     * Get userCreated.
     *
     * @return int
     */
    public function getUserCreated()
    {
        return $this->userCreated;
    }

    /**
     * Get userCreated object.
     *
     * @return object
     */
    public function getUserCreatedObject()
    {
        return $this->userCreatedObject;
    }

    /**
     * Set lastUser.
     *
     * @param int|object $lastUser
     *
     * @return $this
     */
    public function setLastUser($lastUser)
    {
        if (\is_object($lastUser)) {
            $this->lastUserObject = $lastUser;
            $this->lastUser = $lastUser->getId();
        } else {
            $this->lastUserObject = null;
            $this->lastUser = $lastUser;
        }

        return $this;
    }

    /**
     * Get lastUser.
     *
     * @return int
     */
    public function getLastUser()
    {
        return $this->lastUser;
    }

    /**
     * Get lastUser object.
     *
     * @return UserInterface
     */
    public function getLastUserObject()
    {
        return $this->lastUserObject;
    }

    /**
     * Set lastMessage.
     *
     * @param \DateTime $lastMessage
     *
     * @return $this
     */
    public function setLastMessage($lastMessage)
    {
        $this->lastMessage = $lastMessage;

        return $this;
    }

    /**
     * Get lastMessage.
     *
     * @return \DateTime
     */
    public function getLastMessage()
    {
        return $this->lastMessage;
    }

    /**
     * Set createdAt.
     *
     * @param \DateTime $createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set subject.
     *
     * @param string $subject
     *
     * @return $this
     */
    public function setSubject($subject)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Get subject.
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Add message.
     *
     * @param TicketMessageInterface $message
     *
     * @return $this
     */
    public function addMessage(TicketMessageInterface $message)
    {
        $this->messages[] = $message;

        return $this;
    }

    /**
     * Remove message.
     *
     * @param TicketMessageInterface $message
     *
     * @return $this
     */
    public function removeMessage(TicketMessageInterface $message)
    {
        $this->messages->removeElement($message);

        return $this;
    }

    /**
     * Get messages.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMessages()
    {
        return $this->messages;
    }
}

Tests/Fixtures/Entity/Ticket.php
<?php

declare(strict_types=1);

/*
 * This file is part of HackzillaTicketBundle package.
 *
 * (c) Daniel Platt <github@ofdan.co.uk>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Hackzilla\Bundle\TicketBundle\Tests\Fixtures\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Hackzilla\Bundle\TicketBundle\Model\TicketInterface;
use Hackzilla\Bundle\TicketBundle\Model\TicketTrait;

/**
 * @author Javier Spagnoletti <phansys@gmail.com>
 * @author Daniel Platt <github@ofdan.co.uk>
 */
#[ORM\Entity]
class Ticket implements TicketInterface
{
    use TicketTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private \DateTimeInterface $lastMessage;

    #[ORM\Column(type: Types::TEXT, nullable: false)]
    private string $subject;

    #[ORM\Column(type: Types::INTEGER, nullable: false)]
    private int $status;

    #[ORM\Column(type: Types::INTEGER, nullable: false)]
    private int $priority;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private \DateTimeInterface $createdAt;

    /**
     * @var Collection<int, TicketMessage>
     */
    #[ORM\OneToMany(targetEntity: TicketMessage::class, mappedBy: 'ticket')]
    private Collection $messages;

    #[ORM\ManyToOne(targetEntity: User::class)]
    private ?User $userCreated = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    private ?User $lastUser = null;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
}

Tests/Fixtures/Entity/User.php
<?php

declare(strict_types=1);

/*
 * This file is part of HackzillaTicketBundle package.
 *
 * (c) Daniel Platt <github@ofdan.co.uk>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Hackzilla\Bundle\TicketBundle\Tests\Fixtures\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Hackzilla\Bundle\TicketBundle\Model\UserInterface as TicketBundleUserInterface;

/**
 * @author Javier Spagnoletti <phansys@gmail.com>
 * @author Daniel Platt <github@ofdan.co.uk>
 */
#[ORM\Entity]
#[ORM\Table(name: '`user`')]
class User implements TicketBundleUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column(type: Types::JSON)]
    private array $roles = [];

    #[ORM\Column(type: Types::STRING)]
    private ?string $password = null;

    public function __toString(): string
    {
        return $this->getUserIdentifier();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

Form/TicketType.php
<?php

namespace Hackzilla\Bundle\TicketBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Hackzilla\Interfaces\User\UserInterface;

class TicketType extends AbstractType
{

    private $_userManager;

    public function __construct(UserInterface $userManager)
    {
        $this->_userManager = $userManager;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('subject', 'text', array(
                'label' => 'LABEL_SUBJECT'
            ))
            ->add('messages', 'collection', array(
                'type' => new TicketMessageType($this->_userManager, true),
                'label' => false,
                'allow_add' => true,
            ));
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Hackzilla\Bundle\TicketBundle\Entity\Ticket'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'hackzilla_bundle_ticketbundle_tickettype';
    }

}

Form/Type/TicketType.php
<?php

declare(strict_types=1);

/*
 * This file is part of HackzillaTicketBundle package.
 *
 * (c) Daniel Platt <github@ofdan.co.uk>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Hackzilla\Bundle\TicketBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class TicketType extends AbstractType
{
    public function __construct(protected string $ticketClass)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'subject',
                TextType::class,
                [
                    'label' => 'LABEL_SUBJECT',
                ],
            )
            ->add(
                'messages',
                CollectionType::class,
                [
                    'entry_type' => TicketMessageType::class,
                    'entry_options' => [
                        'new_ticket' => true,
                    ],
                    'label' => false,
                    'allow_add' => true,
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'data_class' => $this->ticketClass,
                'translation_domain' => 'HackzillaTicketBundle',
            ]
        );
    }

    public function getBlockPrefix(): string
    {
        return 'ticket';
    }
}

Resources/views/Ticket/index.html.twig
{% extends '@HackzillaTicket/layout.html.twig' %}
{% import hackzilla_ticket.templates.macros as macros %}

{% block hackzilla_ticket_content -%}
    <h1>{{ 'HEADING_TICKET_LIST'|trans({}, translationDomain) }}</h1>

    <div class="row">
        <div class="col-xs-4">
            <div class="btn-group">
                <a href="{{ path('hackzilla_ticket', {'state': 'STATUS_OPEN'|trans({}, translationDomain)}) }}"
                   class="btn btn-default {{ ticketState != 'STATUS_CLOSED'|trans({}, translationDomain) ? 'active' : '' }}">{{ 'STATUS_OPEN'|trans({}, translationDomain)|upper }}</a>
                <a href="{{ path('hackzilla_ticket', {'state': 'STATUS_CLOSED'|trans({}, translationDomain)}) }}"
                   class="btn btn-default {{ ticketState == 'STATUS_CLOSED'|trans({}, translationDomain) ? 'active' : '' }}">{{ 'STATUS_CLOSED'|trans({}, translationDomain)|upper }}</a>
            </div>
        </div>

        <div class="col-xs-4 text-center">
            <div class="btn-group">
                <a href="{{ path('hackzilla_ticket') }}"
                   class="btn btn-default {{ ticketPriority is null ? 'active' : '' }}"><span
                            class="glyphicon glyphicon-remove"></span></a>
                <a href="{{ path('hackzilla_ticket', {'priority': 'PRIORITY_HIGH'|trans({}, translationDomain)}) }}"
                   class="btn btn-danger {{ ticketPriority == 'PRIORITY_HIGH'|trans({}, translationDomain) ? 'active' : '' }}">{{ 'PRIORITY_HIGH'|trans({}, translationDomain)|upper }}</a>
                <a href="{{ path('hackzilla_ticket', {'priority': 'PRIORITY_MEDIUM'|trans({}, translationDomain)}) }}"
                   class="btn btn-warning {{ ticketPriority == 'PRIORITY_MEDIUM'|trans({}, translationDomain) ? 'active' : '' }}">{{ 'PRIORITY_MEDIUM'|trans({}, translationDomain)|upper }}</a>
                <a href="{{ path('hackzilla_ticket', {'priority': 'PRIORITY_LOW'|trans({}, translationDomain)}) }}"
                   class="btn btn-info {{ ticketPriority == 'PRIORITY_LOW'|trans({}, translationDomain) ? 'active' : '' }}">{{ 'PRIORITY_LOW'|trans({}, translationDomain)|upper }}</a>
            </div>
        </div>

        <div class="col-xs-4 text-right">
            <div class="btn-group">
                <a href="{{ path('hackzilla_ticket_new') }}" class="btn btn-primary"><span
                            class="glyphicon glyphicon-plus"></span> {{ 'BUTTON_NEW'|trans({}, translationDomain) }}</a>
            </div>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th class="col-xs-1">{{ knp_pagination_sortable(pagination, 'HEADING_TICKET'|trans({}, translationDomain), 't.id') }}</th>
            <th{% if pagination.isSorted('t.subject') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_SUBJECT'|trans({}, translationDomain), 't.subject') }}</th>
            <th{% if pagination.isSorted('u.email') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_AUTHOR'|trans({}, translationDomain), 'u.email') }}</th>
            <th{% if pagination.isSorted('t.status') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_STATUS'|trans({}, translationDomain), 't.status') }}</th>
            <th{% if pagination.isSorted('t.priority') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_PRIORITY'|trans({}, translationDomain), 't.priority') }}</th>
            <th{% if pagination.isSorted('t.modified') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_MODIFIED'|trans({}, translationDomain), 't.lastMessage') }}</th>
            <th{% if pagination.isSorted('t.created') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_CREATED'|trans({}, translationDomain), 't.createdAt') }}</th>
        </tr>
        </thead>
        <tbody>
        {% for entity in pagination %}
            <tr>
                <td><a href="{{ path('hackzilla_ticket_show', { 'ticketId': entity.id }) }}">{{ entity.id }}</a></td>
                <td><a href="{{ path('hackzilla_ticket_show', { 'ticketId': entity.id }) }}">{{ entity.subject }}</a></td>
                <td>{{ entity.userCreated }}</td>
                <td>{{ macros.status_btn(entity.status, entity.statusString|trans({}, translationDomain), true, translationDomain) }}</td>
                <td>{{ macros.priority_btn(entity.priority, entity.priorityString|trans({}, translationDomain), true, translationDomain) }}</td>
                <td>{% if entity.lastMessage %}{{ entity.lastMessage|date('LABEL_DATE_TIME_FORMAT'|trans({}, translationDomain)) }}{% endif %}</td>
                <td>{% if entity.createdAt %}{{ entity.createdAt|date('LABEL_DATE_TIME_FORMAT'|trans({}, translationDomain)) }}{% endif %}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">{{ 'MESSAGE_NO_TICKETS'|trans({}, translationDomain) }}.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navigation text-right">
        {{ knp_pagination_render(pagination, '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig') }}
    </div>

{% endblock %}

Resources/views/Ticket/new.html.twig
{% extends '@HackzillaTicket/layout.html.twig' %}

{% block hackzilla_ticket_content -%}
    <h1>{{ 'HEADING_NEW_TICKET'|trans({}, translationDomain) }}</h1>

    <div class="well well-sm">
        {{ form_start(form, {'method': 'POST', 'action': path('hackzilla_ticket_create')}) }}
            <div class="form-group row">
                {{ form_label(form.subject, '', { 'label_attr': {'class': 'col-lg-2 col-md-2 col-sm-2 control-label'} }) }}
                <div class="col-lg-8 col-md-8 col-sm-8">
                    {{ form_widget(form.subject, { 'attr': {'class': 'form-control', 'placeholder': 'LABEL_ENTER_SUBJECT' } }) }}
                    {{ form_errors(form.subject) }}
                </div>
            </div>

            {% if form.messages|length == 0 %}
                {% include hackzilla_ticket.templates.prototype with {'form': form.messages.vars.prototype} %}
            {% else %}
                {% include hackzilla_ticket.templates.prototype with {'form': form.messages.__name__} %}
            {% endif %}

            {{ form_rest(form) }}

            <div class="form-group row">
                <div class="col-lg-offset-2 col-lg-10 col-md-offset-2 col-md-10 col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">{{ 'BUTTON_CREATE'|trans({}, translationDomain) }}</button>

                    <a href="{{ path('hackzilla_ticket') }}" class="btn btn-default">
                        {{ 'BUTTON_BACK_TO_LIST'|trans({}, translationDomain) }}
                    </a>
                </div>
            </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

Resources/views/Ticket/prototype.html.twig
<div class="form-group row">
    {{ form_label(form.message, '', { 'label_attr': {'class': 'col-lg-2 col-md-2 col-sm-2 control-label'} }) }}
    <div class="col-lg-8 col-md-8 col-sm-8">
        {{ form_widget(form.message, { 'attr': {'class': 'form-control', 'placeholder': 'LABEL_ENTER_DETAILS', 'rows': '5'} }) }}
        {{ form_errors(form.message) }}
    </div>
</div>

<div class="form-group row">
    {{ form_label(form.priority, '', { 'label_attr': {'class': 'col-lg-2 col-md-2 col-sm-2 control-label'} }) }}
    <div class="col-lg-3 col-md-3 col-sm-3">
        {{ form_widget(form.priority, { 'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.priority) }}
    </div>
</div>

{% if form.status is defined %}
    <div class="form-group row">
        {{ form_label(form.status, '', { 'label_attr': {'class': 'col-lg-2 col-md-2 col-sm-2 control-label'} }) }}
        <div class="col-lg-3 col-md-3 col-sm-3">
            {% if form.status.vars.block_prefixes.1 == 'checkbox' %}
                {{ form_widget(form.status) }}
            {% else %}
                {{ form_widget(form.status, { 'attr': {'class': 'form-control'} }) }}
            {% endif %}
            {{ form_errors(form.status) }}
        </div>
    </div>
{% endif %}

Resources/views/Ticket/show.html.twig
{% extends '@HackzillaTicket/layout.html.twig' %}
{% import hackzilla_ticket.templates.macros as macros %}

{% block hackzilla_ticket_content -%}

    <p>
        <a href="{{ path('hackzilla_ticket') }}" class="btn btn-default">{{ 'BUTTON_BACK_TO_LIST'|trans({}, translationDomain) }}</a>
    </p>

    <h1>
        {{ macros.status_btn(ticket.status, ticket.statusString|trans({}, translationDomain), false, translationDomain) }}
        {{ macros.priority_btn(ticket.priority, ticket.priorityString|trans({}, translationDomain), false, translationDomain) }}
        <small>#{{ ticket.id }}</small>
        - {{ ticket.subject }}
    </h1>

    <p>
        <i>{{ 'LABEL_CREATED_BY'|trans({}, translationDomain) }} {{ ticket.userCreated.userIdentifier|default('ANONYMOUS'|trans({}, translationDomain)) }}
            , {{ ticket.createdAt|date('LABEL_DATE_FORMAT'|trans({}, translationDomain)) }}</i>
        {# <br />{{ 'LABEL_PRIORITY'|trans({}, translationDomain) }} <span class="label label-{{ ticket.priority == 0 ? 'default' : (ticket.priority == 20 ? 'primary' : (ticket.priority == 21 ? 'warning' : 'danger')) }}">{{ ticket.priorityString|trans({}, translationDomain) }}</span> #}
    </p>


    {# <h3>{{ 'HEADING_TICKET_THREAD'|trans({}, translationDomain) }}</h3> #}
    {% set previousStatus = null %}
    {% set previousPriority = null %}

    {% for message in ticket.messages %}

        {% if previousStatus and previousStatus != message.status %}
            {{ macros.status_alert(message.status, message.statusString|trans({}, translationDomain), translationDomain) }}
        {% endif %}

        {% if previousPriority and previousPriority != message.priority %}
            {{ macros.priority_alert(message.priority, message.priorityString|trans({}, translationDomain), translationDomain) }}
        {% endif %}

        {% if message.message|length > 0 %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ message.user.userIdentifier | default('ANONYMOUS'|trans({}, translationDomain)) }}
                    {# <br />{{ 'LABEL_PRIORITY'|trans({}, translationDomain) }} <span class="label label-{{ message.priority == 0 ? 'default' : (message.priority == 20 ? 'primary' : (message.priority == 21 ? 'warning' : 'danger')) }}">{{ message.priorityString|trans({}, translationDomain) }}</span> #}
                    {# <br />{{ 'LABEL_STATUS'|trans({}, translationDomain) }} <span class="label label-{{ message.status ? 'success' : 'danger' }}">{{ message.statusString|trans({}, translationDomain) }}</span> #}

                    <span class="pull-right">
                        {% if message.user and "ROLE_ADMIN" in message.user.roles %}<span class="label label-danger">{{ 'LABEL_ADMIN'|trans({}, translationDomain) }}</span> {% endif %}
                        <small><i>{{ message.createdAt|date('LABEL_DATE_TIME_FORMAT'|trans({}, translationDomain)) }}</i></small>
                    </span>
                </div>
                <div class="panel-body">
                    {{ message.message|nl2br }}
                    {% if(hasTicketFeature('attachment')) %}
                        {% include hackzilla_ticket.templates.show_attachment with {'message': message} %}
                    {% endif %}
                </div>
            </div>
        {% endif %}

        {% set previousStatus = message.status %}
        {% set previousPriority = message.priority %}
    {% endfor %}

    <hr />

    {% if form is defined %}
        <div class="well well-sm">
            {{ form_start(form, {'method': 'POST', 'action': path('hackzilla_ticket_reply', {'ticketId': ticket.id})}) }}
            {% include hackzilla_ticket.templates.prototype with {'form': form} %}

            {{ form_rest(form) }}

            <p class="form_actions">
                <button type="submit" class="btn btn-primary">{{ 'BUTTON_UPDATE'|trans({}, translationDomain) }}</button>
            </p>
            {{ form_end(form) }}
        </div>
    {% endif %}

    {% if delete_form is defined %}
        {{ form_start(delete_form, {'method': 'POST', 'action': path('hackzilla_ticket_delete', {'ticketId': ticket.id}), 'attr': {'class': 'text-right'}}) }}
        <input type="hidden" name="_method" value="DELETE"/>
        {{ form_widget(delete_form) }}

        <button type="submit" class="btn btn-danger">{{ 'BUTTON_DELETE'|trans({}, translationDomain) }}</button>
        {{ form_end(delete_form) }}
    {% endif %}

{% endblock %}

Resources/views/Ticket/show_attachment.html.twig
{% import hackzilla_ticket.templates.macros as macros %}
{% if message.attachmentName %}
<br>
<div class="ticket_attachment">
    <span class="glyphicon glyphicon-paperclip"></span>
    <a href="{{ path('hackzilla_ticket_attachment', {ticketMessageId: message.id}) }}">{{ message.attachmentName }}</a>
    {% if message.attachmentSize is not null %}{{ macros.bytesToSize(message.attachmentSize) }}{% endif %}
</div>
{% endif %}